package app.betterhabits.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// "Pond" palette: frog green primary, lily-pad secondary, lotus-pink tertiary accent.
// Used unless the user opts in to dynamic (wallpaper) colour.

internal val LightColors = lightColorScheme(
    primary = Color(0xFF2E6B3A),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFB4F1B4),
    onPrimaryContainer = Color(0xFF00210A),
    secondary = Color(0xFF52634F),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFD5E8CF),
    onSecondaryContainer = Color(0xFF101F0F),
    tertiary = Color(0xFF8B4A5E),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFD9E1),
    onTertiaryContainer = Color(0xFF3A0719),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF410002),
    background = Color(0xFFF6FBF1),
    onBackground = Color(0xFF181D17),
    surface = Color(0xFFF6FBF1),
    onSurface = Color(0xFF181D17),
    surfaceVariant = Color(0xFFDDE5D8),
    onSurfaceVariant = Color(0xFF424940),
    outline = Color(0xFF72796F),
    outlineVariant = Color(0xFFC1C9BD),
    inverseSurface = Color(0xFF2D322B),
    inverseOnSurface = Color(0xFFEEF2E9),
    inversePrimary = Color(0xFF99D49A),
    surfaceDim = Color(0xFFD7DBD2),
    surfaceBright = Color(0xFFF6FBF1),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF0F5EB),
    surfaceContainer = Color(0xFFEAEFE5),
    surfaceContainerHigh = Color(0xFFE5E9E0),
    surfaceContainerHighest = Color(0xFFDFE4DA),
)

internal val DarkColors = darkColorScheme(
    primary = Color(0xFF99D49A),
    onPrimary = Color(0xFF003915),
    primaryContainer = Color(0xFF135224),
    onPrimaryContainer = Color(0xFFB4F1B4),
    secondary = Color(0xFFB9CCB4),
    onSecondary = Color(0xFF253423),
    secondaryContainer = Color(0xFF3B4B38),
    onSecondaryContainer = Color(0xFFD5E8CF),
    tertiary = Color(0xFFFFB1C5),
    onTertiary = Color(0xFF541D30),
    tertiaryContainer = Color(0xFF703346),
    onTertiaryContainer = Color(0xFFFFD9E1),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    background = Color(0xFF0F150F),
    onBackground = Color(0xFFDFE4DA),
    surface = Color(0xFF0F150F),
    onSurface = Color(0xFFDFE4DA),
    surfaceVariant = Color(0xFF424940),
    onSurfaceVariant = Color(0xFFC1C9BD),
    outline = Color(0xFF8C9388),
    outlineVariant = Color(0xFF424940),
    inverseSurface = Color(0xFFDFE4DA),
    inverseOnSurface = Color(0xFF2D322B),
    inversePrimary = Color(0xFF2E6B3A),
    surfaceDim = Color(0xFF0F150F),
    surfaceBright = Color(0xFF353B33),
    surfaceContainerLowest = Color(0xFF0A100A),
    surfaceContainerLow = Color(0xFF171D16),
    surfaceContainer = Color(0xFF1B211A),
    surfaceContainerHigh = Color(0xFF262B24),
    surfaceContainerHighest = Color(0xFF30362E),
)
